Repository DhanushaPerera07/CTSE-Flutter-Project-Code4v2, pull requests merged in 2022-04, with the labels that each got.

#26 Get all the updates to the deveop branch
  lib/dal/destination_dao.dart
  lib/dal/restaurant_dao.dart
  lib/dal/transportation_dao.dart
  lib/data/data.dart
  lib/main.dart
  lib/model/destination.dart
  lib/model/restaurant.dart
  lib/model/transportation.dart
  lib/objectbox-model.json
  lib/view/Destination_add_edit_view.dart
  lib/view/battery_info_view.dart
  lib/view/destination_view.dart
  lib/view/restaurant_add_edit_view.dart
  lib/view/restaurant_view.dart
  lib/view/transportation_add_edit_view.dart
  lib/view/transportation_view.dart
Labels: enhancement, feature

#28 Enhancement/27/add more properties to hotel crud
  lib/data/data.dart
  lib/main.dart
  lib/model/hotel.dart
  lib/objectbox-model.json
  lib/view/battery_info_view.dart
  lib/view/destination_add_edit_view.dart
  lib/view/home_view.dart
  lib/view/hotel_add_edit_view.dart
  lib/view/hotel_view.dart
  lib/view_component/menu_card_view.dart
Labels: enhancement

#29 Develop
  lib/data/data.dart
  lib/main.dart
  lib/model/hotel.dart
  lib/objectbox-model.json
  lib/view/battery_info_view.dart
  lib/view/destination_add_edit_view.dart
  lib/view/home_view.dart
  lib/view/hotel_add_edit_view.dart
  lib/view/hotel_view.dart
  lib/view_component/menu_card_view.dart
Labels: enhancement

#31 Transportation enhancement
  lib/data/data.dart
  lib/model/transportation.dart
  lib/objectbox-model.json
  lib/view/restaurant_add_edit_view.dart
  lib/view/transportation_add_edit_view.dart
  lib/view/transportation_view.dart
Labels: enhancement

#32 Transportation enhancement
  lib/data/data.dart
  lib/model/transportation.dart
  lib/objectbox-model.json
  lib/view/restaurant_add_edit_view.dart
  lib/view/transportation_add_edit_view.dart
  lib/view/transportation_view.dart
Labels: enhancement

#33 added new features to the app
  lib/data/data.dart
  lib/main.dart
  lib/model/restaurant.dart
  lib/objectbox-model.json
  lib/view/restaurant_add_edit_view.dart
  lib/view/restaurant_view.dart
  pubspec.yaml
Labels: enhancement

#34 Get main changes
  lib/data/data.dart
  lib/main.dart
  lib/model/restaurant.dart
  lib/objectbox-model.json
  lib/view/restaurant_add_edit_view.dart
  lib/view/restaurant_view.dart
  pubspec.yaml
Labels: enhancement

#37 Enhancement/32/code refactoring
  lib/main.dart
  lib/view/battery_info_view.dart
  lib/view/restaurant_view.dart
  pubspec.yaml
Labels: enhancement

#38 Develop
  lib/main.dart
  lib/view/battery_info_view.dart
  pubspec.yaml
Labels: enhancement

#42 Bug/fix navigation battery
  lib/main.dart
  lib/view/battery_info_view.dart
  lib/view/destination_add_edit_view.dart
  lib/view/home_view.dart
  lib/view/hotel_add_edit_view.dart
  lib/view/restaurant_add_edit_view.dart
  lib/view/transportation_add_edit_view.dart
Labels: bug

#43 Develop
  lib/main.dart
  lib/view/battery_info_view.dart
  lib/view/destination_add_edit_view.dart
  lib/view/hotel_add_edit_view.dart
  lib/view/restaurant_add_edit_view.dart
  lib/view/transportation_add_edit_view.dart
Labels: bug
